export const FETCH_POSTS = 'POSTS/FETCH_POSTS';
export const FETCH_PAGE_POSTS = 'POSTS/FECTH_PAGE_POSTS';
export const FILTER_POSTS = 'POSTS/FILTER_POSTS';
export const FETCHED_POSTS = 'POSTS/FETCHED_POSTS'
export const FETCH_TOPICS = 'TOPICS/FETCH_TOPICS';
export const FETCHED_TOPICS = 'TOPICS/FETCHED_TOPICS'
export const FETCH_TAGS = 'TAG/FETCH_TAG';
export const FETCHED_TAGS = 'TAG/FETCHED_TAG'
export const FETCH_POST = 'POST/FETCH_POST';
export const FETCHED_POST = 'POST/FETCHED_POST'
export const FETCH_COMMENTS = 'COMMENTS/FETCH_COMMENTS';
export const FETCHED_COMMENTS = 'COMMENTS/FETCHED_COMMENTS'
 