export const CHANGE_LOCALE = 'LOCALE/CHANGE_LOCALE';
export const MODAL_OPEN = 'APP/MODAL_OPEN';
export const MODAL_CLOSE = 'APP/MODAL_CLOSE';
export const DRAWER_OPEN = 'APP/DRAWER_OPEN';
export const DRAWER_CLOSE = 'APP/DRAWER_CLOSE';
